apiVersion: devices.kubeedge.io/v1alpha1
kind: Device
metadata:
  name: led-light-instance-01
  labels:
    model: led-light
spec:
  deviceModelRef:
    name: led-light
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: ''
            operator: In
            values:
              - edge-node1
status:
  twins:
    - propertyName: power-status
      desired:
        metadata:
          type: string
        value: 'OFF'
