apiVersion: devices.kubeedge.io/v1alpha1
kind: DeviceModel
metadata:
  name: led-light
  namespace: default
spec:
  properties:
    - name: power-status
      type:
        string:
          accessMode: ReadWrite
          defaultValue: 'OFF'
    - name: gpio-pin-number
      type:
        int:
          accessMode: ReadOnly
          defaultValue: 18
